// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

 static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-AK43QgEEgDdh4MP5kbf7LGgqZmjHFvI',
    appId: '1:9519663292:web:40513725744f4bf1a268b9',
    messagingSenderId: '9519663292',
    projectId: 'fluttermobileia',
    authDomain: 'fluttermobileia.firebaseapp.com',
    storageBucket: 'fluttermobileia.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1CzCcTZGD_FaiUhbMMfmGwQa6y-04dPg',
    appId: '1:9519663292:android:dcc1effa1202191fa268b9',
    messagingSenderId: '9519663292',
    projectId: 'fluttermobileia',
    storageBucket: 'fluttermobileia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJW3JqBJD71d0kpzEhlir-4hx4SeauLPs',
    appId: '1:9519663292:ios:19afa2e7fe916271a268b9',
    messagingSenderId: '9519663292',
    projectId: 'fluttermobileia',
    storageBucket: 'fluttermobileia.appspot.com',
    iosBundleId: 'com.example.recognizemeIa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJW3JqBJD71d0kpzEhlir-4hx4SeauLPs',
    appId: '1:9519663292:ios:b8fa3dd029710c85a268b9',
    messagingSenderId: '9519663292',
    projectId: 'fluttermobileia',
    storageBucket: 'fluttermobileia.appspot.com',
    iosBundleId: 'com.example.recognizemeIa.RunnerTests',
  );
}
